name: portfolio
description: "Kshitij Sharma — Personal Portfolio & Blog"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  timeago: ^3.6.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.2.1
  file_picker: 8.1.7
  mime: ^1.0.6
  http_parser: ^4.1.2
  web_socket_channel: ^3.0.1
  video_player: ^2.9.2
  chewie: ^1.8.5
  crop_your_image: ^1.1.0-alpha.5
  uuid: ^4.4.0
  supabase_flutter: ^2.8.1
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
